.snyk
Jenkinsfile
app/data/models/debt-data.js
app/data/models/invoice-line.js
app/data/models/payment-request.js
app/data/models/quality-check.js
app/data/models/scheme.js
changelog/db.changelog-1.1.xml
changelog/db.changelog.xml
package-lock.json
package.json

Request editor database setup

---

Jenkinsfile
app/index.js
package-lock.json
package.json

https://eaflood.atlassian.net/browse/SFI-1603

Add timestamp to logs

---

app/debt/index.js
app/debt/save-debt.js
app/payment-request/get-payment-request.js
app/payment-request/index.js
app/plugins/router.js
app/routes/enrich-request.js
app/routes/models/enrich-request.js
app/routes/schemas/date.js
app/routes/schemas/enrich-request.js
app/utils/date-formatter.js
app/views/enrich-request.njk
app/views/enrich.njk
changelog/db.changelog-1.3.xml
changelog/db.changelog.xml
package-lock.json
package.json
test/integration/narrow/routes/enrich-request.test.js

Pay-1540: Attach debt information to pending request

---

app/data/models/debt-data.js
app/debt-types.js
app/debt/get-debts.js
app/models/capture-debt.js
app/processing/conversion/convert-debt-type.js
app/processing/conversion/index.js
app/routes/models/enrich-request.js
app/views/capture.njk
package.json
test/unit/processing/convert-debt-type.test.js

https://eaflood.atlassian.net/browse/SFI-1772

Display full named debt types in capture screen

---

app/routes/capture-debt.js
app/routes/models/capture-debt.js
package.json

https://eaflood.atlassian.net/browse/SFI-1792

Moving ViewModel folder

---

app/config/index.js
app/debt/attach-debt-information.js
app/event/index.js
app/event/send-enrich-request-blocked-event.js
package-lock.json
package.json
test/integration/local/debt/attach-debt-information.test.js
test/integration/local/payment-request/get-invoice-lines-of-payment-request.test.js
test/integration/local/payment-request/process-payment-request.test.js
test/integration/local/payment-request/update-quality-check-status.test.js
test/unit/event/send-enrich-request-blocked-event.test.js

https://eaflood.atlassian.net/browse/SFI-1447

Send event for stuck debt requests

---

app/debt/attach-debt-information.js
package-lock.json
package.json
test/integration/local/debt/attach-debt-information.test.js

https://eaflood.atlassian.net/browse/SFI-1952

Fix to allow debt enrich block event to send through

---

app/frontend/css/application.scss
app/routes/models/capture-debt.js
app/views/enrich.njk
app/views/macros/ledger-check.njk
app/views/macros/payment-request-header.njk
app/views/macros/payment-request-invoice-lines.njk
app/views/manual-ledger-check.njk
app/views/manual-ledger.njk
app/views/quality-check.njk
package.json

https://eaflood.atlassian.net/browse/SFI-1964
Also covers
https://eaflood.atlassian.net/browse/SFI-1963

Ledger types should not disappear if change is made

---

app/routes/models/enrich-request.js
app/routes/schemas/date.js
app/routes/schemas/scheme.js
package-lock.json
package.json
test/integration/narrow/routes/capture-debt.test.js
test/integration/narrow/routes/enrich-request.test.js

https://eaflood.atlassian.net/browse/SFI-2050﻿

Prevent invalid dates

---

app/processing/ledger/create-split-invoice-number.js
app/routes/models/capture-debt.js
app/routes/schemas/application-identifier.js
app/routes/schemas/scheme.js
app/schemes.js
package.json
test/integration/narrow/routes/capture-debt.test.js
test/unit/processing/split-ledger.test.js

https://eaflood.atlassian.net/browse/SFI-1973

Support Lump Sums invoice

---

.snyk
app/plugins/logging.js
package-lock.json
package.json

https://eaflood.atlassian.net/browse/SFI-2155

Upgrade Hapi Pino

---

app/debt/attach-debt-information-if-exists.js
app/payment-request/process-payment-request.js
package.json
test/integration/local/debt/attach-debt-information.test.js

https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/121665

Simplify attachDebtInfo

---

app/manual-ledger/ledger-review.js
app/processing/debt/capture-debt-data.js
app/processing/debt/index.js
app/processing/enrich/enrich-request.js
app/processing/enrich/index.js
app/processing/validate-date.js
app/routes/capture-debt.js
app/routes/enrich-request.js
app/routes/manual-ledger-review.js
package.json
test/unit/manual-ledger/ledger-review.test.js

https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/177527

reduce code chunks in routes files

---

app/config/index.js
app/convert-to-csv.js
app/extract/index.js
app/extract/map-extract.js
app/routes/capture.js
app/views/capture.njk
app/views/debts-report-unavailable.njk
package.json
test/integration/narrow/routes/capture.test.js
test/unit/convert-to-csv.test.js
test/unit/extract/map-extract.test.js

https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/297643

add export functionality

---

app/extract/map-extract.js
package.json
test/unit/extract/map-extract.test.js

https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/297643

fix display issues

---

app/routes/schemas/capture-debt.js
app/routes/schemas/debt-year.js
package.json

https://dev.azure.com/defragovuk/DEFRA-FFC/_workitems/edit/292811

refactor debt date schema

---

app/routes/manual-ledger.js
package.json
test/integration/narrow/routes/manual-ledger.test.js

https://eaflood.atlassian.net/jira/software/projects/DOC/issues/DOC-702

amend filter function

---

app/routes/models/enrich-request.js
app/routes/schemas/date.js
package.json
test/integration/narrow/routes/capture-debt.test.js
test/integration/narrow/routes/enrich-request.test.js

https://eaflood.atlassian.net/browse/DOC-792

amend error message for date validation

---

app/debt/attach-debt-information-if-exists.js
app/debt/check-debts-by-enrichment.js
app/debt/check-debts.js
app/manual-ledger/attach-debt-to-manual-ledger.js
app/manual-ledger/check-for-debt-data.js
app/routes/schemas/application-identifier.js
package.json
test/integration/local/debt/check-debts.test.js
test/integration/narrow/routes/capture-debt.test.js
test/unit/messaging/publish-quality-checked-payment-requests.test.js

https://eaflood.atlassian.net/browse/DOC-869

allow exact and numeric match on both agreement and contract number

---

app/constants/schemes.js
app/processing/ledger/create-split-invoice-number.js
app/routes/capture-debt.js
app/routes/schemas/application-identifier.js
app/routes/schemas/scheme.js
changelog/db.changelog-1.30.xml
changelog/db.changelog.xml
package.json
test/integration/narrow/routes/capture-debt.test.js
test/unit/processing/split-ledger.test.js

https://eaflood.atlassian.net/browse/DOC-671

add delinked

---

app/routes/models/capture-debt.js
package.json

https://eaflood.atlassian.net/browse/DOC-850

amend hint text app identifier

---

app/constants/schemes.js
app/processing/ledger/create-split-invoice-number.js
app/routes/schemas/scheme.js
changelog/db.changelog-1.31.xml
changelog/db.changelog.xml
package-lock.json
package.json
test/integration/narrow/routes/capture-debt.test.js
test/unit/processing/split-ledger.test.js

https://eaflood.atlassian.net/browse/DOC-1037
https://eaflood.atlassian.net/browse/DOC-1045

add sfi expanded

---

app/manual-ledger/get-manual-ledgers.js
app/payment-request/get-payment-request.js
app/quality-check/get-quality-checks.js
app/routes/capture.js
app/routes/enrich.js
app/routes/manual-ledger.js
app/routes/quality-check.js
app/views/enrich.njk
app/views/manual-ledger.njk
app/views/quality-check.njk
package.json
test/unit/manual-ledger/get-manual-ledgers.test.js
test/unit/payment-request/get-payment-request.test.js

https://eaflood.atlassian.net/browse/DOC-640

introduce pagination to improve memory utilisation and performance

---

app/routes/quality-check.js
package.json
test/integration/narrow/routes/quality-check.test.js

https://eaflood.atlassian.net/browse/DOC-1340

FRN search fix for quality checks

---

README.md
docker-compose.debug.yaml
docker-compose.migrate.yaml
docker-compose.override.yaml
docker-compose.test.debug.yaml
docker-compose.test.watch.yaml
docker-compose.test.yaml
docker-compose.yaml
package.json
scripts/start
scripts/test

- Removed version
- moved from docker-compose to docker compose

DOC-1419 : moved command docker-compose to docker compose and removed version

---

Dockerfile
package.json

https://eaflood.atlassian.net/browse/DOC-1728

fix local build issue

---

app/debt/get-debts.js
app/routes/capture.js
app/views/capture.njk
package-lock.json
package.json

https://eaflood.atlassian.net/browse/DOC-959

Doc 959 bug search should exclude pagination when results can be found on pages greater than the number set in the dropdown

---

app/auth/is-in-role.js
app/debt/get-debts.js
app/manual-ledger/get-manual-ledger-requests.js
app/manual-ledger/get-manual-ledgers.js
app/payment-request/get-payment-request.js
app/processing/object-check.js
app/processing/scheme/get-schemes.js
app/quality-check/get-quality-checks.js
package-lock.json
package.json

https://eaflood.atlassian.net/browse/DOC-923

fixed 6 x for of loops , constant nullishness and a chain expression

---

.github/workflows/main.yml
app/constants/scheme-names.js
app/constants/status-codes.js
app/routes/authenticate.js
app/routes/capture-debt.js
app/routes/capture.js
app/routes/dev-auth.js
app/routes/enrich-request.js
app/routes/enrich.js
app/routes/healthy.js
app/routes/healthz.js
app/routes/login.js
app/routes/manual-ledger-check.js
app/routes/manual-ledger-review.js
app/routes/manual-ledger.js
app/routes/models/search-combined.js
app/routes/quality-check.js
app/routes/schemas/capture-by-frn-or-scheme.js
app/routes/schemas/scheme.js
app/views/capture.njk
app/views/macros/search-combined.njk
package-lock.json
package.json
test/integration/narrow/routes/capture.test.js

https://eaflood.atlassian.net/browse/DOC-1595

allow debt data filtering by scheme

---

app/routes/capture.js
app/views/capture.njk
package-lock.json
package.json

https://eaflood.atlassian.net/browse/DOC-1846
https://eaflood.atlassian.net/browse/DOC-1847

amend prev/next behaviour, fix search issues
